import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { TopMenu } from '@/components/ui/top-menu';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col gap-4 antialiased`}
      >
        <div className="grid grid-rows-[60px_1fr_20px] items-center justify-items-center gap-8 font-[family-name:var(--font-geist-sans)] ">
          <TopMenu />
          {children}
        </div>
      </body>
    </html>
  );
}
